In [29]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import time

In [42]:
#cv2.imshow('Original',frame)
def detect(c):
    peri=cv2.arcLength(c,True)
    approx=cv2.approxPolyDP(c,0.04*peri,True)
    if(len(approx)==7):
        return True
    else:
        return False

In [28]:
template=cv2.imread('arrow.jpg')
temp,corners = detect(template,7)
print(corners)
cv2.imshow('window', temp)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[744 203]]

 [[744 360]]

 [[329 359]]

 [[329 204]]

 [[746 138]]

 [[746 427]]

 [[846 282]]]


In [41]:
def cont(frame):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    img=cv2.GaussianBlur(gray,(3,3),0)
    ret,thresh = cv2.threshold(img,127,255,0)
    im,contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    
    for c in contours:
        flag=detect(c)
        if flag:
            cv2.drawContours(img, c, -1, (0,255,0), 3)
    return img

In [43]:
def main():
    last_time = time.time()
    v=cv2.VideoCapture(1)
    while(True):
        ret,frame=v.read()
        new_screen =cont(frame)
        print('Loop took {} seconds'.format(time.time()-last_time))
        last_time = time.time()
        cv2.imshow('window', new_screen)
        
        #cv2.imshow('window2', cv2.cvtColor(screen, cv2.COLOR_BGR2RGB))
        if cv2.waitKey(25) & 0xFF == ord('q'):
            cv2.destroyAllWindows()
            break

In [44]:
main()

Loop took 1.168395757675171 seconds
Loop took 1.0977764129638672 seconds
Loop took 0.06557559967041016 seconds
Loop took 0.04334712028503418 seconds
Loop took 0.05083894729614258 seconds
Loop took 0.04996776580810547 seconds
Loop took 0.04415583610534668 seconds
Loop took 0.06497859954833984 seconds
Loop took 0.046694278717041016 seconds
Loop took 0.04801750183105469 seconds
Loop took 0.04913163185119629 seconds
Loop took 0.059090614318847656 seconds
Loop took 0.045151710510253906 seconds
Loop took 0.050232648849487305 seconds
Loop took 0.05365133285522461 seconds
Loop took 0.06217527389526367 seconds
Loop took 0.04233908653259277 seconds
Loop took 0.04712486267089844 seconds
Loop took 0.05013847351074219 seconds
Loop took 0.05213499069213867 seconds
Loop took 0.052977561950683594 seconds
Loop took 0.05086946487426758 seconds
Loop took 0.060404300689697266 seconds
Loop took 0.07118916511535645 seconds
Loop took 0.03814411163330078 seconds
Loop took 0.02924370765686035 seconds
Loop took

Loop took 0.050603628158569336 seconds
Loop took 0.03509259223937988 seconds
Loop took 0.031084537506103516 seconds
Loop took 0.041066646575927734 seconds
Loop took 0.04308295249938965 seconds
Loop took 0.054955244064331055 seconds
Loop took 0.05024552345275879 seconds
Loop took 0.04530215263366699 seconds
Loop took 0.04597759246826172 seconds
Loop took 0.046552181243896484 seconds
Loop took 0.046112060546875 seconds
Loop took 0.03973197937011719 seconds
Loop took 0.03110814094543457 seconds
Loop took 0.037378549575805664 seconds
Loop took 0.04641914367675781 seconds
Loop took 0.046716928482055664 seconds
Loop took 0.04612326622009277 seconds
Loop took 0.04557609558105469 seconds
Loop took 0.04639863967895508 seconds
Loop took 0.04545283317565918 seconds
Loop took 0.0432286262512207 seconds
Loop took 0.04444575309753418 seconds
Loop took 0.032033443450927734 seconds
Loop took 0.04617142677307129 seconds
Loop took 0.032048940658569336 seconds
Loop took 0.04953122138977051 seconds
Loop t

Loop took 0.04916810989379883 seconds
Loop took 0.03909707069396973 seconds
Loop took 0.04752922058105469 seconds
Loop took 0.0690155029296875 seconds
Loop took 0.04731106758117676 seconds
Loop took 0.048128604888916016 seconds
Loop took 0.04667973518371582 seconds
Loop took 0.06368851661682129 seconds
Loop took 0.049405813217163086 seconds
Loop took 0.04788923263549805 seconds
Loop took 0.047136545181274414 seconds
Loop took 0.06176471710205078 seconds
Loop took 0.047373294830322266 seconds
Loop took 0.04852700233459473 seconds
Loop took 0.04812502861022949 seconds
Loop took 0.061890363693237305 seconds
Loop took 0.04815053939819336 seconds
Loop took 0.04700446128845215 seconds
Loop took 0.05113577842712402 seconds
Loop took 0.0590670108795166 seconds
Loop took 0.04845690727233887 seconds
Loop took 0.04732370376586914 seconds
Loop took 0.04995584487915039 seconds
Loop took 0.06245756149291992 seconds
Loop took 0.04654264450073242 seconds
Loop took 0.04776811599731445 seconds
Loop took